{
  global:
    SherpaOnnxCreateKeywordSpotter;
    SherpaOnnxDecodeKeywordStream;
    SherpaOnnxGetKeywordResult;
    SherpaOnnxResetKeywordStream;
    SherpaOnnxGetVersionStr;
    SherpaOnnxGetOnnxruntimeVersionStr;
    SherpaOnnxGetGitSha1;
    SherpaOnnxDestroyKeywordSpotter;
    SherpaOnnxCreateKeywordStream;
    SherpaOnnxDestroyOnlineStream;
    SherpaOnnxOnlineStreamAcceptWaveform;
    SherpaOnnxOnlineStreamInputFinished;
    SherpaOnnxIsKeywordStreamReady;
    SherpaOnnxDestroyKeywordResult;
  local: *;
};
