from __future__ import annotations


PATH_PURITY_LOSS_WEIGHT_DEFAULT = 0.0
PATH_PURITY_MARGIN_DEFAULT = 0.10
PATH_PURITY_MARGIN_MAX = 2.0
PATH_PURITY_POLICY = "ordered-active-wake-competitor-hinge-v1"

ORDERED_TOKEN_SCOPE_ALL_NONEMPTY = "all-nonempty-targets-v1"
ORDERED_TOKEN_SCOPE_EXACT_WAKE = "exact-configured-wake-targets-v1"
ORDERED_TOKEN_SCOPE_DEFAULT = ORDERED_TOKEN_SCOPE_ALL_NONEMPTY
ORDERED_TOKEN_SCOPES = frozenset(
    {
        ORDERED_TOKEN_SCOPE_ALL_NONEMPTY,
        ORDERED_TOKEN_SCOPE_EXACT_WAKE,
    }
)

SEQUENCE_MARGIN_NEGATIVE_POLICY_SPARSE = "sparse-chronological-v1"
SEQUENCE_MARGIN_NEGATIVE_POLICY_RUNTIME_EXECUTABLE = "runtime-executable-v1"
SEQUENCE_MARGIN_NEGATIVE_POLICY_DEFAULT = SEQUENCE_MARGIN_NEGATIVE_POLICY_SPARSE
SEQUENCE_MARGIN_NEGATIVE_POLICIES = frozenset(
    {
        SEQUENCE_MARGIN_NEGATIVE_POLICY_SPARSE,
        SEQUENCE_MARGIN_NEGATIVE_POLICY_RUNTIME_EXECUTABLE,
    }
)
