from __future__ import annotations


CTC_OBJECTIVE_POLICY_STANDARD = "standard-v1"
CTC_OBJECTIVE_POLICY_LABEL_PRIOR = "posterior-marginal-label-prior-v1"
CTC_OBJECTIVE_POLICY_DEFAULT = CTC_OBJECTIVE_POLICY_STANDARD
CTC_OBJECTIVE_POLICIES = frozenset(
    {
        CTC_OBJECTIVE_POLICY_STANDARD,
        CTC_OBJECTIVE_POLICY_LABEL_PRIOR,
    }
)


PATH_PURITY_LOSS_WEIGHT_DEFAULT = 0.0
PATH_PURITY_MARGIN_DEFAULT = 0.10
PATH_PURITY_MARGIN_MAX = 2.0
PATH_PURITY_POLICY = "ordered-active-wake-competitor-hinge-v1"

ORDERED_TOKEN_SCOPE_ALL_NONEMPTY = "all-nonempty-targets-v1"
ORDERED_TOKEN_SCOPE_EXACT_WAKE = "exact-configured-wake-targets-v1"
ORDERED_TOKEN_SCOPE_DEFAULT = ORDERED_TOKEN_SCOPE_ALL_NONEMPTY
ORDERED_TOKEN_SCOPES = frozenset(
    {
        ORDERED_TOKEN_SCOPE_ALL_NONEMPTY,
        ORDERED_TOKEN_SCOPE_EXACT_WAKE,
    }
)

SEQUENCE_MARGIN_POSITIVE_POLICY_SPARSE = "sparse-chronological-v1"
SEQUENCE_MARGIN_POSITIVE_POLICY_RUNTIME_SEARCH_ALIGNED = "runtime-search-aligned-v1"
SEQUENCE_MARGIN_POSITIVE_POLICY_CTC_KEYWORD_COMPETITION = (
    "ctc-keyword-competition-v1"
)
SEQUENCE_MARGIN_POSITIVE_POLICY_CTC_TOKEN_STATE_TARGET_BLANK = (
    "ctc-token-state-target-blank-v1"
)
SEQUENCE_MARGIN_POSITIVE_POLICY_DEFAULT = SEQUENCE_MARGIN_POSITIVE_POLICY_SPARSE
# Rejected policies remain implemented so retained evidence can be recomputed,
# but only fixed-logit-qualified candidates may be selected by new training.
SEQUENCE_MARGIN_POSITIVE_POLICIES = frozenset(
    {
        SEQUENCE_MARGIN_POSITIVE_POLICY_SPARSE,
        SEQUENCE_MARGIN_POSITIVE_POLICY_CTC_TOKEN_STATE_TARGET_BLANK,
    }
)
SEQUENCE_MARGIN_POSITIVE_IMPLEMENTATIONS = frozenset(
    {
        SEQUENCE_MARGIN_POSITIVE_POLICY_SPARSE,
        SEQUENCE_MARGIN_POSITIVE_POLICY_CTC_TOKEN_STATE_TARGET_BLANK,
        SEQUENCE_MARGIN_POSITIVE_POLICY_RUNTIME_SEARCH_ALIGNED,
        SEQUENCE_MARGIN_POSITIVE_POLICY_CTC_KEYWORD_COMPETITION,
    }
)

SEQUENCE_MARGIN_NEGATIVE_POLICY_SPARSE = "sparse-chronological-v1"
SEQUENCE_MARGIN_NEGATIVE_POLICY_RUNTIME_EXECUTABLE = "runtime-executable-v1"
SEQUENCE_MARGIN_NEGATIVE_POLICY_DEFAULT = SEQUENCE_MARGIN_NEGATIVE_POLICY_SPARSE
SEQUENCE_MARGIN_NEGATIVE_POLICIES = frozenset(
    {
        SEQUENCE_MARGIN_NEGATIVE_POLICY_SPARSE,
        SEQUENCE_MARGIN_NEGATIVE_POLICY_RUNTIME_EXECUTABLE,
    }
)
