"""Certify input-independent binary64 FFT twiddles using outward Decimal110 intervals."""
from decimal import Decimal as D, Context, ROUND_FLOOR, ROUND_CEILING
from fractions import Fraction
from pathlib import Path
import hashlib
import json
import math

LO = Context(prec=110, rounding=ROUND_FLOOR)
HI = Context(prec=110, rounding=ROUND_CEILING)


def point(x):
    d = D(x)
    return d, d


def add(a, b):
    return LO.add(a[0], b[0]), HI.add(a[1], b[1])


def neg(a):
    return a[1].copy_negate(), a[0].copy_negate()


def sub(a, b):
    return add(a, neg(b))


def mul(a, b):
    return min(LO.multiply(x, y) for x in a for y in b), max(HI.multiply(x, y) for x in a for y in b)


def div_positive(a, b):
    assert b[0] > 0
    reciprocal = LO.divide(D(1), b[1]), HI.divide(D(1), b[0])
    return mul(a, reciprocal)


def atan_inverse(q, terms):
    x = div_positive(point(1), point(q))
    xx = mul(x, x)
    power, result = x, point(0)
    for n in range(terms):
        term = div_positive(power, point(2*n+1))
        result = add(result, term if n % 2 == 0 else neg(term))
        power = mul(power, xx)
    remainder = div_positive(power, point(2*terms+1))[1]
    return add(result, (remainder.copy_negate(), remainder))


def trig(x, sine):
    assert D(0) <= x[0] <= x[1] < D(2)
    xx = mul(x, x)
    term = x if sine else point(1)
    total = term
    for n in range(1, 100):
        denominator = (2*n)*(2*n+1) if sine else (2*n-1)*(2*n)
        term = div_positive(mul(term, xx), point(denominator))
        total = add(total, term if n % 2 == 0 else neg(term))
    assert Fraction(2**200, math.factorial(200)) < Fraction(1, 10**300)
    assert Fraction(2**201, math.factorial(201)) < Fraction(1, 10**300)
    return add(total, (D('-1e-300'), D('1e-300')))


def certify_rne(interval):
    lo, hi = map(Fraction, interval)
    proposed = float(interval[0])
    if lo == hi == 0:
        return 0.0, None
    center = Fraction(proposed)
    lower = (Fraction(math.nextafter(proposed, -math.inf)) + center) / 2
    upper = (Fraction(math.nextafter(proposed, math.inf)) + center) / 2
    if not lower < lo <= hi < upper:
        raise ArithmeticError('Twiddle has no certified unique binary64 RNE cell')
    margin = min(lo-lower, upper-hi)
    return proposed, margin


def generate():
    pi = sub(mul(point(16), atan_inverse(5, 90)), mul(point(4), atan_inverse(239, 30)))
    assert D(3) < pi[0] <= pi[1] < D(4)
    cosines, sines, certificates, margins = [], [], [], []
    for k in range(256):
        if k == 0:
            co, si = point(1), point(0)
        elif k == 128:
            co, si = point(0), point(-1)
        else:
            angle = div_positive(mul(pi, point(k if k < 128 else 256-k)), point(256))
            co, si = trig(angle, False), neg(trig(angle, True))
            if k > 128:
                co = neg(co)
        cv, cm = certify_rne(co)
        sv, sm = certify_rne(si)
        cosines.append(cv.hex())
        sines.append(sv.hex())
        certificates.append({'k': k, 'cos': list(map(str, co)), 'sin': list(map(str, si)), 'cos_hex': cv.hex(), 'sin_hex': sv.hex()})
        margins.extend(m for m in (cm, sm) if m is not None)
    header = '/* Generated by generate_twiddles.py; exact certified binary64 RNE roots. */\n'
    for name, values in [('cos', cosines), ('sin', sines)]:
        header += f'static const double donor_fft64_{name}[256] = {{\n'
        for i in range(0, 256, 4):
            header += ' ' + ', '.join(values[i:i+4]) + ',\n'
        header += '};\n'
    report = {'schema': 'fft64-twiddle-interval-certificate-v1', 'precision': 110,
              'pi_interval': list(map(str, pi)), 'atan_terms': {'5': 90, '239': 30},
              'trig_terms': 100, 'trig_absolute_remainder': '1e-300',
              'all_unique_rne_cells': True,
              'minimum_rounding_cell_margin_fraction': str(min(margins)),
              'header_sha256': hashlib.sha256(header.encode()).hexdigest(),
              'certificates': certificates}
    return header, report


if __name__ == '__main__':
    root = Path(__file__).resolve().parent
    header, report = generate()
    assert report['header_sha256'] == 'aed3eea430d875049ae160eba9bd8fe0589a5ab42758f9d56a37913792d26074'
    with (root/'src/fft64_twiddles.h').open('x') as f:
        f.write(header)
    with (root/'twiddle-certificate.json').open('x') as f:
        json.dump(report, f, indent=2, sort_keys=True)
        f.write('\n')
    print(json.dumps({k: v for k, v in report.items() if k != 'certificates'}))
