#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import math
import pathlib
import re
import struct
import sys

from kws_vocab import load_tokens, vocab_fingerprint, vocab_size

MAX_KEYWORDS = 16
MAX_TOKENS_PER_KEYWORD = 16
PACK_VERSION = 3
PACK_HEADER_BYTES = 24
PACK_RECORD_BYTES = 48
PREFIX_POLICIES = {"immediate": 0, "longest": 1, "grace": 2}


def text_to_pinyin(text: str) -> list[str]:
    if not re.search(r"[\u3400-\u9fff]", text):
        return text.strip().split()
    try:
        from pypinyin import Style, lazy_pinyin
    except ImportError as exc:
        raise RuntimeError(
            "pypinyin required for implicit Chinese conversion; "
            "use explicit TSV tokens for production"
        ) from exc
    return lazy_pinyin(
        text,
        style=Style.TONE3,
        neutral_tone_with_five=True,
        errors="default",
    )


def byte_value(value: str, label: str) -> int:
    result = int(value)
    if result < 0 or result > 255:
        raise ValueError(f"{label} must be in 0..255")
    return result


def parse_keywords(path: pathlib.Path, token_map: dict[str, int]) -> list[dict]:
    result: list[dict] = []
    seen_ids: set[int] = set()
    seen_sequences: set[tuple[int, ...]] = set()
    for n, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        cols = raw.split("\t")
        if len(cols) not in (3, 4, 5, 6, 7, 8):
            raise ValueError(f"{path}:{n}: expected 3..8 TSV columns")
        kid = int(cols[0])
        text = cols[1].strip()
        threshold = float(cols[2])
        if not math.isfinite(threshold):
            raise ValueError(f"{text}: threshold must be finite")
        tokens = (
            cols[3].split()
            if len(cols) >= 4 and cols[3].strip()
            else text_to_pinyin(text)
        )
        min_trailing_blanks = byte_value(cols[4], f"{text}: min_trailing_blanks") if len(cols) >= 5 and cols[4].strip() else 0
        priority = byte_value(cols[5], f"{text}: priority") if len(cols) >= 6 and cols[5].strip() else 0
        policy_name = cols[6].strip().lower() if len(cols) >= 7 and cols[6].strip() else "immediate"
        if policy_name not in PREFIX_POLICIES:
            raise ValueError(f"{text}: prefix_policy must be immediate, longest or grace")
        grace_frames = byte_value(cols[7], f"{text}: grace_frames") if len(cols) >= 8 and cols[7].strip() else 0
        prefix_policy = PREFIX_POLICIES[policy_name]
        if prefix_policy == PREFIX_POLICIES["longest"] and min_trailing_blanks == 0:
            min_trailing_blanks = 1
        if prefix_policy == PREFIX_POLICIES["grace"] and grace_frames == 0:
            grace_frames = 3
        if kid in seen_ids:
            raise ValueError(f"duplicate keyword id {kid}")
        if kid < 0 or kid > 0xFFFFFFFF:
            raise ValueError(f"{text}: keyword id must fit uint32")
        if not 0.0 < threshold < 1.0:
            raise ValueError(f"{text}: threshold must be in (0,1)")
        if not 1 <= len(tokens) <= MAX_TOKENS_PER_KEYWORD:
            raise ValueError(
                f"{text}: token length must be 1..{MAX_TOKENS_PER_KEYWORD}"
            )
        missing = [token for token in tokens if token not in token_map]
        if missing:
            raise ValueError(f"{text}: unknown tokens: {', '.join(missing)}")
        ids = [token_map[token] for token in tokens]
        if any(token_id == 0 for token_id in ids):
            raise ValueError("blank token cannot appear in keyword")
        sequence = tuple(ids)
        if sequence in seen_sequences:
            raise ValueError(f"{text}: duplicate acoustic token path")
        seen_ids.add(kid)
        seen_sequences.add(sequence)
        result.append(
            {
                "id": kid,
                "text": text,
                "threshold": threshold,
                "tokens": tokens,
                "token_ids": ids,
                "min_trailing_blanks": min_trailing_blanks,
                "priority": priority,
                "prefix_policy": policy_name,
                "prefix_policy_id": prefix_policy,
                "grace_frames": grace_frames,
            }
        )
    if not result:
        raise ValueError("keyword file contains no keywords")
    if len(result) > MAX_KEYWORDS:
        raise ValueError(f"runtime supports at most {MAX_KEYWORDS} keywords")
    return result


def emit_header(items: list[dict], fingerprint: int, out: pathlib.Path) -> None:
    lines = [
        "/* Generated by tools/compile_keywords.py. Do not edit. */",
        "#ifndef KWS_GENERATED_KEYWORDS_H",
        "#define KWS_GENERATED_KEYWORDS_H",
        "#include <stddef.h>",
        "#include <stdint.h>",
        '#include "kws_pipeline/kws.h"',
        "",
        "static const uint64_t kws_generated_vocab_fingerprint = "
        f"UINT64_C(0x{fingerprint:016x});",
        "",
    ]
    for n, item in enumerate(items):
        values = ", ".join(f"{value}u" for value in item["token_ids"])
        lines.append(f"static const uint16_t kws_kw_{n}_tokens[] = {{{values}}};")
    lines += ["", "static const kws_keyword_t kws_generated_keywords[] = {"]
    for n, item in enumerate(items):
        lines.append(
            "  {"
            f"{item['id']}u, kws_kw_{n}_tokens, "
            f"(uint16_t)(sizeof(kws_kw_{n}_tokens) / sizeof(kws_kw_{n}_tokens[0])), "
            f"{item['threshold']:.6f}f, {item['min_trailing_blanks']}u, "
            f"{item['priority']}u, {item['prefix_policy_id']}u, {item['grace_frames']}u"
            f"}}, /* {item['text']} */"
        )
    lines += [
        "};",
        "static const size_t kws_generated_keyword_count = "
        "sizeof(kws_generated_keywords) / sizeof(kws_generated_keywords[0]);",
        "",
        "#endif",
        "",
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")


def emit_pack(
    items: list[dict], token_map: dict[str, int], out: pathlib.Path
) -> None:
    size = vocab_size(token_map)
    fingerprint = vocab_fingerprint(token_map)
    total_bytes = PACK_HEADER_BYTES + len(items) * PACK_RECORD_BYTES
    blob = bytearray(
        struct.pack(
            "<4sHHHHIQ",
            b"KWKP",
            PACK_VERSION,
            PACK_HEADER_BYTES,
            len(items),
            size,
            total_bytes,
            fingerprint,
        )
    )
    for item in items:
        padded = list(item["token_ids"]) + [0] * (
            MAX_TOKENS_PER_KEYWORD - len(item["token_ids"])
        )
        blob.extend(
            struct.pack(
                "<IfHBBBBH16H",
                item["id"],
                item["threshold"],
                len(item["token_ids"]),
                item["min_trailing_blanks"],
                item["priority"],
                item["prefix_policy_id"],
                item["grace_frames"],
                0,
                *padded,
            )
        )
    if len(blob) != total_bytes:
        raise RuntimeError("internal keyword-pack size mismatch")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(blob)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tokens", required=True, type=pathlib.Path)
    parser.add_argument("--keywords", required=True, type=pathlib.Path)
    parser.add_argument("--out-header", type=pathlib.Path)
    parser.add_argument("--out-pack", type=pathlib.Path)
    parser.add_argument("--out-json", type=pathlib.Path)
    args = parser.parse_args()
    if not (args.out_header or args.out_pack or args.out_json):
        parser.error("at least one of --out-header, --out-pack or --out-json is required")

    token_map = load_tokens(args.tokens)
    items = parse_keywords(args.keywords, token_map)
    fingerprint = vocab_fingerprint(token_map)
    if args.out_header:
        emit_header(items, fingerprint, args.out_header)
    if args.out_pack:
        emit_pack(items, token_map, args.out_pack)
    if args.out_json:
        args.out_json.parent.mkdir(parents=True, exist_ok=True)
        args.out_json.write_text(
            json.dumps(
                {
                    "vocab_size": vocab_size(token_map),
                    "vocab_fingerprint": f"0x{fingerprint:016x}",
                    "keywords": items,
                },
                ensure_ascii=False,
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
    print(
        f"compiled {len(items)} keyword(s), vocab={vocab_size(token_map)}, "
        f"fingerprint=0x{fingerprint:016x}"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ValueError, RuntimeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(2)
